
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 23 10:08:41 GMT-06:00 2016
//----------------------------------------------------

package Example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GRight = 6;
  public static final int NUMBER = 11;
  public static final int GLeft = 5;
  public static final int EOF = 0;
  public static final int Activa = 7;
  public static final int Avanza = 4;
  public static final int Inicio = 3;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int Semi = 2;
  public static final int LPAREN = 9;
  public static final int Fin = 8;
}

