
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 08 13:35:43 CST 2016
//----------------------------------------------------

package automatas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GIZ = 6;
  public static final int ACT = 7;
  public static final int TERM = 8;
  public static final int NUMBER = 11;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int INIC = 3;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int AVAN = 4;
  public static final int GDE = 5;
  public static final int LPAREN = 9;
}

